### ISSUE TITLE
调用stop，没有收到player finish的通知。

### ISSUE THREAD

**Issue by carusd** [ksvc/KSYMediaPlayer_iOS#100]
根据 KSYMediaPlayback 里的对 stop 方法的描述，调用 stop 之后应该会收到 MPMoviePlayerPlaybackDidFinishNotification 的通知。
但是实践中发现没有收到这个通知，反而是收到了 MPMoviePlayerPlaybackStateDidChangeNotification 通知，在这里断点可以发现播放器的状态是 MPMoviePlaybackStateStopped 。
想问问是不是这里文档的说明是不是已经失效了？如果是，我就不用回去检查用法有没有问题了。

播放器版本：2.9.4.1，iOS 11，iPhone 7p

**Comment by mayudong1** [comment]
目前看来确实是这种表现，应该跟用法没关系，以实际表现为准吧
文档中的描述可能已经不准确了，但是没有及时更新
谢谢反馈

**Comment by carusd** [comment]
ok, case closed
