### ISSUE TITLE
请问这是什么原因啊?本地视频url可以播放,但是提前获取视频信息,就出现KSYProbe: avformat_open_input failed!

### ISSUE THREAD

**Issue by 0neDirection** [ksvc/KSYMediaPlayer_iOS#11]

**Comment by fpzeng** [comment]
提前获取，是指调用kSYProbe提取本地视频url文件吗？
请加入qq群574179720，提供一下本地文件，方便我们分析。

**Comment by fpzeng** [comment]
嗯，已经确认该视频资源在本地可以直接播放，但是probe失败。原因还在分析中

**Comment by fpzeng** [comment]
原因已经确认，当前不支持本地文件的probe。该功能会在春节后第一个版本release。
谢谢！

**Comment by fpzeng** [comment]
https://github.com/ksvc/KSYMediaPlayer_iOS/releases/tag/v1.9.5
已经修复，请试用

**Comment by 0neDirection** [comment]
现在确实可以获取视频信息了,不过好像获取视频缩略图还没有修复,KSYGetThumbnail: avformat_open_input failed!

**Comment by mayudong1** [comment]
测试了获取缩略图没有问题啊，能详细描述一下出问题时的操作吗？

**Comment by shixuemei** [comment]
不好意思，2.0.0版本中我们会修复获取视频缩略图失败的问题，谢谢！

**Comment by 0neDirection** [comment]
没事,自己已经解决了

**Comment by shixuemei** [comment]
新发布的v2.0.0版本中已经修复该问题
