### ISSUE TITLE
SDK目前不支持udp的rtsp播放

### ISSUE THREAD

**Issue by JKTerry** [ksvc/KSYMediaPlayer_iOS#12]
SDK目前不支持udp的rtsp播放

**Comment by fpzeng** [comment]
该功能已经在测试回归中，预期1月23日前进入release。
我们上线release时，会及时通知您。谢谢！

**Comment by fpzeng** [comment]
https://github.com/ksvc/KSYMediaPlayer_iOS/releases/tag/v1.9.5
已经修复，请使用
