### ISSUE TITLE
请问可以把bufferSizeMax属性的下限降低到0吗，需要个暂停加载缓存的功能。

### ISSUE THREAD

**Issue by chenkaiwei** [ksvc/KSYMediaPlayer_iOS#18]
如题，当用户切换网络到运营商网络时，需要弹出一个提示框让用户确认使用后才继续加载。这时候理论上应该停止缓存的（虽然用户一般感知不到，但还是希望能有），在目前基础上只要调整下bufferSizeMax下限就可以了，谢谢。

**Comment by fpzeng** [comment]
嗯，这个我把需求交给产品评估一下，有进展我会在这里回复

**Comment by fpzeng** [comment]
已经上线，请试用：
https://github.com/ksvc/KSYMediaPlayer_iOS/releases/tag/v2.0.1
