### ISSUE TITLE
播放过程中分辨率改变了

### ISSUE THREAD

**Issue by liuyi520it** [ksvc/KSYMediaPlayer_iOS#22]
播放过程中有的推流地址分辨率改变了，监听了尺寸改变的通知，可SDK没有好像没有提供解决方案，可用此地址rtmp://rlive.jia.360.cn/live_jia_public/36060744749放到Demo中测试

**Comment by mayudong1** [comment]
这个属于播放SDK的bug，使用硬解时对该流分辨率解析出错，导致播放的分辨率错误，该问题会在下一个release的版本中修正

**Comment by fpzeng** [comment]
可以使用软解避免这个问题，待我们下个版本发布后，再切回硬解

**Comment by fpzeng** [comment]
新版本已经上线：https://github.com/ksvc/KSYMediaPlayer_iOS/releases/tag/v2.0.3
