### ISSUE TITLE
KSYMediaPlayer_iOS  沒有看到能加上http header 的功能

### ISSUE THREAD

**Issue by janyo1201** [ksvc/KSYMediaPlayer_iOS#23]
hi 大神們
我在KSYMediaPlayer_Android 有看到它是能支援 PlayerHttpHeader 的功能
https://github.com/ksvc/KSYMediaPlayer_Android/wiki/PlayerHttpHeader

但在 KSYMediaPlayer_iOS  沒有看到能加上http header

**Comment by shixuemei** [comment]
下个版本我们会增加这个功能，请及时关注，谢谢

**Comment by fpzeng** [comment]
https://github.com/ksvc/KSYMediaPlayer_iOS/wiki/setHttpHeader
wiki接口如上，请等待release note

**Comment by fpzeng** [comment]
请使用我们的v2.0.3版本：
