### ISSUE TITLE
shouldAutoplay 和 prepareToPlay

### ISSUE THREAD

**Issue by adronfan** [ksvc/KSYMediaPlayer_iOS#26]
shouldAutoplay在prepareToPlay后设置无效。
有场景可能在调用prepareToPlay后发现需要重新设置shouldAutoplay。望处理

**Comment by fpzeng** [comment]
shouldAutoplay决定了prepare完成后，是否需要自动开播，一定需要在prepareToPlay前设置的。
如果需要其他设置，建议监听MPMediaPlaybackIsPreparedToPlayDidChangeNotification ，然后做对应处理。
我们暂时不打算调整该部分逻辑，谢谢。
