### ISSUE TITLE
iOS版本在iphone5手机ios7下运行crash

### ISSUE THREAD

**Issue by kenhowonderful** [ksvc/KSYMediaPlayer_iOS#34]
如图：出现类似诸如“KSYReachabillity.o was built for newer iOS version(8.0) than being linked 7.0”的警告（有数十个），运行在iOS8.1、9.0、10.3的机子上均正常，但运行在iphone5 ios7.1的机子上crash。

![image](https://cloud.githubusercontent.com/assets/28726593/26096959/85ca9c18-3a55-11e7-8380-a0a3d5fc6362.png)

**Comment by shixuemei** [comment]
抱歉，该问题会在2.3.0版本解决，版本大约在6月上旬发布，请关注，谢谢！

**Comment by HaixiaLei** [comment]
原来是这个问题，弄了半天才查出是播放器问题，
但打包没有报错啊，运行才出问题，对xcode表示无语
期待解决 期待解决 期待解决

**Comment by shixuemei** [comment]
v2.3.0版本已上线，该问题已修复，请更新验证，无问题后请close issue, 谢谢！

**Comment by shixuemei** [comment]
已验证无问题
