### ISSUE TITLE
iOS拉流sdk，播放错误时崩溃，而且没有走MPMoviePlayerPlaybackDidFinishNotification此通知

### ISSUE THREAD

**Issue by dream-xue** [ksvc/KSYMediaPlayer_iOS#35]
iOS拉流sdk，播放错误时崩溃，而且没有走MPMoviePlayerPlaybackDidFinishNotification此通知，金山的demo也是如此，播放地址     http://101.200.125.198:10001/jrelax-fs//file/sztx2/80f51e28-b9eb-45d7-8f89-22fc10b5f038/db333de5-7d3b-4927-b06b-ac3581bc521d.mp4

**Comment by mayudong1** [comment]
该问题会在2.3.0版本修正，预计本周或下周会发布

**Comment by shixuemei** [comment]
v2.3.0版本已上线，该问题已修复，请更新验证，无问题后请close issue，谢谢！
