### ISSUE TITLE
Play HLS video with new versions

### ISSUE THREAD

**Issue by manolisep** [ksvc/KSYMediaPlayer_iOS#52]
Hi I updated the lib to the 2.8.0 release, but HLS on demand video doesn't play:
VideoPath: http://wowza.netpoint.com.br/mpires_od/placeholder.mp4/playlist.m3u8

Working just in < 2.0.3 releases.

Can you help me?

Thanks!

**Comment by shixuemei** [comment]
I'm very sorry for that maybe a bug in player SDK, we will fix it as soon as possible。

But if the url doesn't contain ".mp4" string, you can avoid this problem, Could you change it？

**Comment by manolisep** [comment]
Live streams and on demand without ".mp4" it works.

**Comment by shixuemei** [comment]
This problem have been solved in version 2.9.0, you can try it，ths！
