### ISSUE TITLE
AudioSessionCategory 設置

### ISSUE THREAD

**Issue by hc0405** [ksvc/KSYMediaPlayer_iOS#89]
請問可以提供 AVAudioSessionCategoryAmbient 的設置嗎
讓 silent mode 可以靜音

**Comment by mayudong1** [comment]
目前SDK中AudioSession设置的为AVAudioSessionCategoryPlayback，不支持slient mode静音  
这个设置是在player在初始化的时候进行的设置，可以试试在app中在player初始化后将AudioSession重新设置为AVAudioSessionCategoryAmbient
